import { StockItem } from "./types";

export const initialStockData: StockItem[] = [
  {
    id: "S001",
    productId: "P001",
    productName: "School Uniform Set",
    category: "Uniforms",
    minStock: 20,
    maxStock: 100,
    currentStock: 45,
    status: "Normal",
  },
  {
    id: "S002",
    productId: "P002",
    productName: "School P.E. Uniform Set",
    category: "Uniforms",
    minStock: 15,
    maxStock: 80,
    currentStock: 150,
    status: "Normal",
  },
  {
    id: "S003",
    productId: "P003",
    productName: "School ID Lace",
    category: "ID Lace",
    minStock: 10,
    maxStock: 50,
    currentStock: 62,
    status: "Low",
  },
  {
    id: "S004",
    productId: "P004",
    productName: "Test Booklet",
    category: "Booklet",
    minStock: 20,
    maxStock: 100,
    currentStock: 500,
    status: "Normal",
  },
  {
    id: "S005",
    productId: "P005",
    productName: "NSTP Uniform (ROTC)",
    category: "Uniforms",
    minStock: 25,
    maxStock: 120,
    currentStock: 8,
    status: "Critical",
  },
  {
    id: "S006",
    productId: "P006",
    productName: "NSTP Uniform (CWTS)",
    category: "Uniforms",
    minStock: 15,
    maxStock: 60,
    currentStock: 5,
    status: "Critical",
  },
  {
    id: "S007",
    productId: "P007",
    productName: "College Polo",
    category: "Uniforms",
    minStock: 30,
    maxStock: 150,
    currentStock: 85,
    status: "Normal",
  },
  {
    id: "S008",
    productId: "P008",
    productName: "College Blouse",
    category: "Uniforms",
    minStock: 25,
    maxStock: 120,
    currentStock: 95,
    status: "Normal",
  },
];
