import { Order } from "./types";

export const initialOrders: Order[] = [
  {
    id: "1",
    orderNumber: "152456",
    name: "Carlos Martinez",
    items: "Uniforms, ID Lace",
    quantity: 5,
    pickupDate: "Dec 09, 2025",
    status: "Ready",
  },
  {
    id: "2",
    orderNumber: "101230",
    name: "Sofia Garcia",
    items: "Uniforms",
    quantity: 2,
    pickupDate: "Nov 26, 2025",
    status: "Ready",
  },
  {
    id: "3",
    orderNumber: "00006",
    name: "Miguel Torres",
    items: "Booklet",
    quantity: 10,
    pickupDate: "Nov 30, 2025",
    status: "Ready",
  },
  {
    id: "4",
    orderNumber: "189234",
    name: "Ana Reyes",
    items: "School Uniform Set",
    quantity: 3,
    pickupDate: "Dec 12, 2025",
    status: "Ready",
  },
  {
    id: "5",
    orderNumber: "145678",
    name: "Juan Dela Cruz",
    items: "P.E. Uniform",
    quantity: 2,
    pickupDate: "Dec 15, 2025",
    status: "Ready",
  },
  {
    id: "6",
    orderNumber: "198765",
    name: "Christine Brooks",
    items: "NSTP Uniform",
    quantity: 1,
    pickupDate: "Nov 20, 2025",
    status: "Released",
  },
  {
    id: "7",
    orderNumber: "187654",
    name: "Rosie Pearson",
    items: "Test Booklet, ID Lace",
    quantity: 15,
    pickupDate: "Nov 22, 2025",
    status: "Released",
  },
  {
    id: "8",
    orderNumber: "176543",
    name: "Darrell Caldwell",
    items: "College Polo",
    quantity: 4,
    pickupDate: "Nov 25, 2025",
    status: "Released",
  },
];
