import { LogRecord } from "./types";

export const initialLogs: LogRecord[] = [
  {
    id: "1",
    logId: "LOG-001",
    type: "Order",
    category: "Order Created",
    description: "New order ORD-2024-001 created by Maria Santos",
    user: "System",
    timestamp: "2025-01-15 10:30:45",
    status: "Success",
  },
  {
    id: "2",
    logId: "LOG-002",
    type: "Payment",
    category: "Payment Verified",
    description: "GCash payment verified for ORD-2024-003",
    user: "Admin",
    timestamp: "2025-01-15 10:45:22",
    status: "Success",
  },
  {
    id: "3",
    logId: "LOG-003",
    type: "Activity",
    category: "Stock Updated",
    description: "Stock level updated for School Uniform",
    user: "Admin",
    timestamp: "2025-01-15 11:00:08",
    status: "Info",
  },
  {
    id: "4",
    logId: "LOG-004",
    type: "System",
    category: "Low Stock Alert",
    description: "Booklet stock level is critically low (8 units)",
    user: "System",
    timestamp: "2025-01-15 11:15:33",
    status: "Warning",
  },
  {
    id: "5",
    logId: "LOG-005",
    type: "Order",
    category: "Order Released",
    description: "Order ORD-2024-007 released to customer",
    user: "Admin",
    timestamp: "2025-01-15 11:30:45",
    status: "Success",
  },
  {
    id: "6",
    logId: "LOG-006",
    type: "Payment",
    category: "Payment Pending",
    description: "Cash payment pending for ORD-2024-004",
    user: "System",
    timestamp: "2025-01-15 11:45:12",
    status: "Success",
  },
  {
    id: "7",
    logId: "LOG-007",
    type: "Order",
    category: "Order Created",
    description: "New order ORD-2024-008 created by Juan Cruz",
    user: "System",
    timestamp: "2025-01-15 12:00:30",
    status: "Success",
  },
  {
    id: "8",
    logId: "LOG-008",
    type: "Activity",
    category: "Stock Updated",
    description: "Stock level updated for P.E. Uniform",
    user: "Admin",
    timestamp: "2025-01-15 12:15:45",
    status: "Info",
  },
  {
    id: "9",
    logId: "LOG-009",
    type: "Payment",
    category: "Payment Verified",
    description: "Cash payment verified for ORD-2024-005",
    user: "Admin",
    timestamp: "2025-01-15 12:30:22",
    status: "Success",
  },
  {
    id: "10",
    logId: "LOG-010",
    type: "System",
    category: "Low Stock Alert",
    description: "NSTP Uniform (ROTC) stock level is critically low (5 units)",
    user: "System",
    timestamp: "2025-01-15 12:45:18",
    status: "Warning",
  },
];
