import { Order } from "./types";

export const initialOrders: Order[] = [
  {
    id: "1",
    orderNum: "152456",
    name: "Carlos Martinez",
    items: "Uniforms, ID Lace",
    quantity: 5,
    paymentMethod: "GCash",
    paymentStatus: "Pending",
    pickupDate: "Dec 09, 2025",
    stage: "To Confirm",
  },
  {
    id: "2",
    orderNum: "101230",
    name: "Sofia Garcia",
    items: "Uniforms",
    quantity: 2,
    paymentMethod: "GCash",
    paymentStatus: "Pending",
    pickupDate: "Nov 26, 2025",
    stage: "To Confirm",
  },
  {
    id: "3",
    orderNum: "00006",
    name: "Miguel Torres",
    items: "Booklet",
    quantity: 10,
    paymentMethod: "Cash",
    paymentStatus: "Pending",
    pickupDate: "Nov 30, 2025",
    stage: "To Confirm",
  },
  {
    id: "4",
    orderNum: "145623",
    name: "Ana Reyes",
    items: "School Uniform Set",
    quantity: 3,
    paymentMethod: "GCash",
    paymentStatus: "Pending",
    pickupDate: "Dec 15, 2025",
    stage: "To Pay",
  },
  {
    id: "5",
    orderNum: "189034",
    name: "Juan Dela Cruz",
    items: "P.E. Uniform",
    quantity: 2,
    paymentMethod: "Cash",
    paymentStatus: "Pending",
    pickupDate: "Dec 20, 2025",
    stage: "To Pay",
  },
  {
    id: "6",
    orderNum: "123789",
    name: "Maria Santos",
    items: "NSTP Uniform",
    quantity: 1,
    paymentMethod: "GCash",
    paymentStatus: "Verified",
    pickupDate: "Dec 18, 2025",
    stage: "Paid",
  },
  {
    id: "7",
    orderNum: "156890",
    name: "Pedro Garcia",
    items: "Test Booklet, ID Lace",
    quantity: 15,
    paymentMethod: "Cash",
    paymentStatus: "Verified",
    pickupDate: "Dec 22, 2025",
    stage: "Paid",
  },
  {
    id: "8",
    orderNum: "198456",
    name: "Christine Brooks",
    items: "School Uniform Set",
    quantity: 2,
    paymentMethod: "GCash",
    paymentStatus: "Verified",
    pickupDate: "Nov 15, 2025",
    stage: "Completed",
  },
  {
    id: "9",
    orderNum: "187623",
    name: "Rosie Pearson",
    items: "College Polo",
    quantity: 3,
    paymentMethod: "Cash",
    paymentStatus: "Verified",
    pickupDate: "Nov 20, 2025",
    stage: "Completed",
  },
  {
    id: "10",
    orderNum: "176234",
    name: "Darrell Caldwell",
    items: "P.E. Uniform, Booklet",
    quantity: 4,
    paymentMethod: "GCash",
    paymentStatus: "Verified",
    pickupDate: "Nov 25, 2025",
    stage: "Completed",
  },
];
